version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform Intersight Policies - SNMP
  Manages Intersight SNMP Policies
  
  Location in GUI:
  `Policies` » `Create Policy` » `SNMP`
  
  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ### versions.tf
  ```hcl
  {{ include "examples/complete/versions.tf" }}
  ```

  ## Environment Variables

  It is not supported to include sensitive variables in maps or lists.  snmp_traps and snmp_users are lists of object.  So we assign the passwords as a numerical value in the list of object and then that references the variable that has been set as sensitive.  This way the values can be protected in the state file.

  Thus, The SNMP Module may require more Sensitive Variables because SNMP Policies include community strings and authorization and privilege passwords.  In our example the only sensitive value is the auth_password, which was set to `1`.

  If we were to use communities or privilege passwords we would need to add variables for these as well.

  Each type can have up to five variables for authorization passwords, privilege passwords, and trap communities.  You would add them according to your need.
  
  In the table below, you will see the variables snmp_auth_password_[1-5], snmp_privacy_password_[1-5], and snmp_trap_community_[1-5].  Include these additional variables based on what you need to use for communities and passwords.

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable secretkey with value of [your-secret-file-content]
  - Add variable snmp_auth_password_1 with value of [your-auth-password]

  ### Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  export TF_VAR_snmp_auth_password_1=`cat <your-auth-password>`
  ```

  ### Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>""
  $env:TF_VAR_snmp_auth_password_1="<your-auth-password>""
  ```


  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false