version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform Intersight Policies - SNMP
  Manages Intersight SNMP Policies
  
  Location in GUI:
  `Policies` » `Create Policy` » `SNMP`
  
  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ### versions.tf
  ```hcl
  {{ include "examples/complete/versions.tf" }}
  ```

  ## Environment Variables

  The SNMP Module may have many more Sensitive Variables because SNMP Policies include community strings and auth and priv passwords.

  In this example we added the snmp_auth_password_1 because that was the password assigned to the user.  
  
  In the variables.tf, in the main module, you will see many other options you may need to include based on what you need to use for communities and passwords.

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable secretkey with value of [your-secret-file-content]
  - Add variable snmp_auth_password_1 with value of [your-auth-password]

  ### Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  export TF_VAR_snmp_auth_password_1=`cat <your-auth-password>`
  ```

  ### Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>""
  $env:TF_VAR_snmp_auth_password_1="<your-auth-password>""
  ```


  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false